# --- WARNING ---
# This file was generated using 'make configure'. Do not modify this file by hand.
# ---------------

TARGETS := ./build/result/Ethiopia.region \
	./build/result/South_Sudan.region \
	./build/result/Somalia.region \
	./build/result/Kenya.region \
	./build/result/Malawi.region \
	./build/result/Tanzania.region \
	./build/result/Somaliland.region \
	./build/result/Morocco.region \
	./build/result/Western_Sahara.region \
	./build/result/Republic_of_the_Congo.region \
	./build/result/Democratic_Republic_of_the_Congo.region \
	./build/result/Namibia.region \
	./build/result/South_Africa.region \
	./build/result/Libya.region \
	./build/result/Tunisia.region \
	./build/result/Zambia.region \
	./build/result/Sierra_Leone.region \
	./build/result/Guinea.region \
	./build/result/Liberia.region \
	./build/result/Central_African_Republic.region \
	./build/result/Sudan.region \
	./build/result/Djibouti.region \
	./build/result/Eritrea.region \
	./build/result/Ivory_Coast.region \
	./build/result/Mali.region \
	./build/result/Senegal.region \
	./build/result/Nigeria.region \
	./build/result/Benin.region \
	./build/result/Angola.region \
	./build/result/Botswana.region \
	./build/result/Zimbabwe.region \
	./build/result/Chad.region \
	./build/result/Algeria.region \
	./build/result/Mozambique.region \
	./build/result/Eswatini.region \
	./build/result/Burundi.region \
	./build/result/Rwanda.region \
	./build/result/Uganda.region \
	./build/result/Lesotho.region \
	./build/result/Cameroon.region \
	./build/result/Gabon.region \
	./build/result/Niger.region \
	./build/result/Burkina_Faso.region \
	./build/result/Togo.region \
	./build/result/Ghana.region \
	./build/result/Guinea-Bissau.region \
	./build/result/Egypt.region \
	./build/result/Mauritania.region \
	./build/result/Equatorial_Guinea.region \
	./build/result/The_Gambia.region \
	./build/result/Bir_Tawil.region \
	./build/result/Madagascar.region \
	./build/result/Comoros.region \
	./build/result/São_Tomé_and_Príncipe.region \
	./build/result/Cape_Verde.region \
	./build/result/Antarctica.region \
	./build/result/Indonesia.region \
	./build/result/Malaysia.region \
	./build/result/Dhekelia_Cantonment.region \
	./build/result/Cyprus.region \
	./build/result/India.region \
	./build/result/Peoples_Republic_of_China.region \
	./build/result/Israel.region \
	./build/result/Palestine.region \
	./build/result/Lebanon.region \
	./build/result/Syria.region \
	./build/result/South_Korea.region \
	./build/result/North_Korea.region \
	./build/result/Bhutan.region \
	./build/result/Oman.region \
	./build/result/Uzbekistan.region \
	./build/result/Kazakhstan.region \
	./build/result/Tajikistan.region \
	./build/result/Mongolia.region \
	./build/result/Vietnam.region \
	./build/result/Cambodia.region \
	./build/result/United_Arab_Emirates.region \
	./build/result/Georgia.region \
	./build/result/Azerbaijan.region \
	./build/result/Turkey.region \
	./build/result/Laos.region \
	./build/result/Kyrgyzstan.region \
	./build/result/Armenia.region \
	./build/result/Iraq.region \
	./build/result/Iran.region \
	./build/result/Qatar.region \
	./build/result/Saudi_Arabia.region \
	./build/result/Pakistan.region \
	./build/result/Thailand.region \
	./build/result/Kuwait.region \
	./build/result/East_Timor.region \
	./build/result/Brunei.region \
	./build/result/Myanmar.region \
	./build/result/Bangladesh.region \
	./build/result/Afghanistan.region \
	./build/result/Turkmenistan.region \
	./build/result/Jordan.region \
	./build/result/Nepal.region \
	./build/result/Yemen.region \
	./build/result/Hong_Kong.region \
	./build/result/Turkish_Republic_of_Northern_Cyprus.region \
	./build/result/United_Nations_Buffer_Zone_in_Cyprus.region \
	./build/result/Siachen_Glacier.region \
	./build/result/Baikonur.region \
	./build/result/Akrotiri_Sovereign_Base_Area.region \
	./build/result/Philippines.region \
	./build/result/Sri_Lanka.region \
	./build/result/Taiwan.region \
	./build/result/Japan.region \
	./build/result/Australian_Indian_Ocean_Territories.region \
	./build/result/Singapore.region \
	./build/result/Bahrain.region \
	./build/result/Wake_Island.region \
	./build/result/Macau.region \
	./build/result/Scarborough_Shoal.region \
	./build/result/France.region \
	./build/result/Ukraine.region \
	./build/result/Belarus.region \
	./build/result/Lithuania.region \
	./build/result/Russia.region \
	./build/result/Czech_Republic.region \
	./build/result/Germany.region \
	./build/result/Estonia.region \
	./build/result/Latvia.region \
	./build/result/Norway.region \
	./build/result/Sweden.region \
	./build/result/Finland.region \
	./build/result/Luxembourg.region \
	./build/result/Belgium.region \
	./build/result/North_Macedonia.region \
	./build/result/Albania.region \
	./build/result/Kosovo.region \
	./build/result/Spain.region \
	./build/result/Denmark.region \
	./build/result/Romania.region \
	./build/result/Hungary.region \
	./build/result/Slovakia.region \
	./build/result/Poland.region \
	./build/result/Ireland.region \
	./build/result/United_Kingdom.region \
	./build/result/Greece.region \
	./build/result/Austria.region \
	./build/result/Italy.region \
	./build/result/Switzerland.region \
	./build/result/Netherlands.region \
	./build/result/Liechtenstein.region \
	./build/result/Serbia.region \
	./build/result/Croatia.region \
	./build/result/Slovenia.region \
	./build/result/Bulgaria.region \
	./build/result/San_Marino.region \
	./build/result/Monaco.region \
	./build/result/Andorra.region \
	./build/result/Montenegro.region \
	./build/result/Bosnia_and_Herzegovina.region \
	./build/result/Portugal.region \
	./build/result/Moldova.region \
	./build/result/Gibraltar.region \
	./build/result/Vatican_City.region \
	./build/result/Iceland.region \
	./build/result/Malta.region \
	./build/result/Jersey.region \
	./build/result/Guernsey.region \
	./build/result/Isle_of_Man.region \
	./build/result/Åland.region \
	./build/result/Faroe_Islands.region \
	./build/result/Costa_Rica.region \
	./build/result/Nicaragua.region \
	./build/result/Saint_Martin.region \
	./build/result/Sint_Maarten.region \
	./build/result/Haiti.region \
	./build/result/Dominican_Republic.region \
	./build/result/El_Salvador.region \
	./build/result/Guatemala.region \
	./build/result/Guantanamo_Bay_Naval_Base.region \
	./build/result/Cuba.region \
	./build/result/Honduras.region \
	./build/result/United_States_of_America.region \
	./build/result/Canada.region \
	./build/result/Mexico.region \
	./build/result/Belize.region \
	./build/result/Panama.region \
	./build/result/Greenland.region \
	./build/result/Curaçao.region \
	./build/result/Aruba.region \
	./build/result/The_Bahamas.region \
	./build/result/Turks_and_Caicos_Islands.region \
	./build/result/Saint_Pierre_and_Miquelon.region \
	./build/result/Trinidad_and_Tobago.region \
	./build/result/Grenada.region \
	./build/result/Saint_Vincent_and_the_Grenadines.region \
	./build/result/Barbados.region \
	./build/result/Saint_Lucia.region \
	./build/result/Dominica.region \
	./build/result/United_States_Minor_Outlying_Islands.region \
	./build/result/Montserrat.region \
	./build/result/Antigua_and_Barbuda.region \
	./build/result/Saint_Kitts_and_Nevis.region \
	./build/result/United_States_Virgin_Islands.region \
	./build/result/Saint_Barthélemy.region \
	./build/result/Puerto_Rico.region \
	./build/result/Anguilla.region \
	./build/result/British_Virgin_Islands.region \
	./build/result/Jamaica.region \
	./build/result/Cayman_Islands.region \
	./build/result/Bermuda.region \
	./build/result/Bajo_Nuevo_Bank.region \
	./build/result/Serranilla_Bank.region \
	./build/result/Papua_New_Guinea.region \
	./build/result/Australia.region \
	./build/result/Fiji.region \
	./build/result/New_Zealand.region \
	./build/result/New_Caledonia.region \
	./build/result/Pitcairn_Islands.region \
	./build/result/French_Polynesia.region \
	./build/result/Kiribati.region \
	./build/result/Marshall_Islands.region \
	./build/result/Norfolk_Island.region \
	./build/result/Cook_Islands.region \
	./build/result/Tonga.region \
	./build/result/Wallis_and_Futuna.region \
	./build/result/Samoa.region \
	./build/result/Solomon_Islands.region \
	./build/result/Tuvalu.region \
	./build/result/Nauru.region \
	./build/result/Federated_States_of_Micronesia.region \
	./build/result/Vanuatu.region \
	./build/result/Niue.region \
	./build/result/American_Samoa.region \
	./build/result/Palau.region \
	./build/result/Guam.region \
	./build/result/Northern_Mariana_Islands.region \
	./build/result/Coral_Sea_Islands.region \
	./build/result/Ashmore_and_Cartier_Islands.region \
	./build/result/French_Southern_and_Antarctic_Lands.region \
	./build/result/Seychelles.region \
	./build/result/Heard_Island_and_McDonald_Islands.region \
	./build/result/Saint_Helena.region \
	./build/result/Mauritius.region \
	./build/result/British_Indian_Ocean_Territory.region \
	./build/result/Maldives.region \
	./build/result/South_Georgia_and_the_South_Sandwich_Islands.region \
	./build/result/Clipperton_Island.region \
	./build/result/Chile.region \
	./build/result/Bolivia.region \
	./build/result/Peru.region \
	./build/result/Argentina.region \
	./build/result/Suriname.region \
	./build/result/Guyana.region \
	./build/result/Brazil.region \
	./build/result/Uruguay.region \
	./build/result/Ecuador.region \
	./build/result/Colombia.region \
	./build/result/Paraguay.region \
	./build/result/Brazilian_Island.region \
	./build/result/Venezuela.region \
	./build/result/Southern_Patagonian_Ice_Field.region \
	./build/result/Falkland_Islands.region
